apiVersion: v1
kind: Secret
metadata:
  name: minio-dag-runner-credentials
  namespace: helios
type: Opaque
data:
  access-key: ZGFnLXJ1bm5lci1rZXk=     # dag-runner-key
  secret-key: ZGFnLXJ1bm5lci1zZWNyZXQ= # dag-runner-secret
